apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: course-mapper-

commonLabels:
  app:   course-mapper

vars:
- name: MONGODB_SERVICE
  objref:
    apiVersion: v1
    kind: Service
    name: mongodb

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- pvc.yaml
- mongodb/deployment.yaml
- mongodb/service.yaml
- mongodb/pvc.yaml
