apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: course-mapper-

commonLabels:
  app: course-mapper

vars:
- name: MONGODB_SERVICE
  objref:
    apiVersion: v1
    kind: Service
    name: mongodb

resources:
- web/deployment.yaml
- web/service.yaml
- web/pvc.yaml
- mongodb/deployment.yaml
- mongodb/service.yaml
- mongodb/pvc.yaml
