image: docker:stable

options:
  docker: true

pipelines:
  default:
  - step:
      script:
      - apk add --no-cache py-pip bash
      - pip install --no-cache-dir docker-compose
      - docker-compose build
      caches:
      - docker
