version: "3"
services:

  web:
    build: .
    image: ${IMAGE_NAME_PREFIX:-inko/}course-mapper:${IMAGE_TAG:-latest}
    environment:
    - NODE_ENV=production
    - DATABASE=mongodb/course_mapper
    - PORT=3000
    volumes:
    - web-resources:/home/node/app/public/resources
    - web-pa:/home/node/app/public/pa
    - web-img-courses:/home/node/app/public/img/courses
    ports:
    - 3000:3000
    depends_on:
    - mongodb

  mongodb:
    image: mongo
    volumes:
    - mongodb-data:/data/db

  # admin:
  #   image: mrvautin/adminmongo
  #   environment:
  #   - CONN_NAME=course_mapper
  #   - DB_HOST=mongodb
  #   - DB_NAME=course_mapper
  #   - PASSWORD=admin
  #   - PORT=3001
  #   ports:
  #   - 3001:3001

volumes:
  web-resources:
  web-pa:
  web-img-courses:
  mongodb-data:
