version: "3"
services:

  web:
    build: .
    image: ${IMAGE_NAME_PREFIX:-inko/}course-mapper:${IMAGE_TAG:-latest}
    environment:
    - NODE_ENV=production
    - DATABASE=db/course_mapper
    - PORT=3000
    volumes:
    - web-resources:/home/node/app/public/resources
    - web-pa:/home/node/app/public/pa
    - web-img-courses:/home/node/app/public/img/courses
    ports:
    - 3000:3000
    depends_on:
    - db

  db:
    image: mongo
    volumes:
    - db-data:/data/db

volumes:
  web-resources:
  web-pa:
  web-img-courses:
  db-data:
