apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

resources:
- ingress.yaml

namespace:  sc
namePrefix: soco-

commonLabels:
  owner: sc
  stage: prod
commonAnnotations:
  contact: "Ralf Berger <ralf.berger@uni-due.de>"

images:
- name: inko/course-mapper
  newTag: master
