apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

namespace:  sc
namePrefix: soco-
nameSuffix: -dev

commonLabels:
  owner: sc
  stage: dev
commonAnnotations:
  contact: "Ralf Berger <ralf.berger@uni-due.de>"

images:
- name: inko/course-mapper
  newTag: dev

patchesJson6902:
- target:
    group: networking.k8s.io
    version: v1beta1
    kind: Ingress
    name: web
  path: ingress.patch.yaml
